version: '3.7'

services:
  web:
    build: .
    command: python /code/src/manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/code
    ports:
    - 8000:8000
    depends_on:
      - db
    env_file:
      - envs/dev.env
  db:
    image: postgres:latest
    env_file:
      - envs/dev.env
    volumes:
    - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: